# Generated by Django 3.1.4 on 2020-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201211_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Rank',
            field=models.IntegerField(),
        ),
    ]
