# Generated by Django 3.1.4 on 2020-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201211_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Rank',
            field=models.FloatField(),
        ),
    ]
